### ISSUE TITLE
poor performance with two uploaded articles

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#125]
The ML didn't detect any datasets in these two articles, although there are clearly quite a few. The xml is also quite a mess:

http://app.dataseer.ai/dataseer/documents/5f50e290ec87c40c1ef3bd67

http://app.dataseer.ai/dataseer/documents/5f51e8d3ec87c40c1ef3bd69

Since these were someone trying DataSeer out, it would be good to know what went wrong.

**Comment by timvines19** [comment]
The same user tried the second one again and it did much better:

http://app.dataseer.ai/dataseer/documents/5f51ea3aec87c40c1ef3bd6a

**Comment by kermitt2** [comment]
Would you have the used PDF or a link to these PDF by chance?

**Comment by timvines19** [comment]
I searched for the title and found this pdf - it's not the typeset version, but as it doesn't say 'draft' it's not the same as the one that was uploaded. I thought the database was now storing a copy of the pdf? Or is that just the Dev server version?

[cjes-2020-0092.pdf](https://github.com/DataSeer/dataseer-web/files/5178362/cjes-2020-0092.pdf)

**Comment by kermitt2** [comment]
Yes for the first document, it's not the same PDF, but for this one the problem is that Grobid is finding figures everywhere so too much regular text/paragraphs is not considered and no dataset sentences found. 

For the second document, I found a PDF which looks the same (at ResearchGate) but it's again not exactly the same. I don't know why it did not work the first time for the user, It's always working for me and I can't reproduce the problem. 

About storing the PDF, this will come with issue #74, which is work in progress (only available after merging and redeployed, first in dev, then in prod when you give the go).
