### ISSUE TITLE
Create dedicated Springer Nature Production server

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#128]
the Pilot with SN will begin very soon and we need to have their dedicated server ready

**Comment by kermitt2** [comment]
The server at the address dataseer-nature-springer.science-miner.com is up and running since around 2 months normally, but we could change the address for a dataseer.ai sub-domain... the hard question being which name for the sub-domain :)

**Comment by kermitt2** [comment]
https://dataseer-springer-nature.science-miner.com -> be sure to use `https` - is it not working ?

For the dataseer.ai, it has to be a subdomain I think, because I cannot map a path on the existing subdomain app.dataseer.ai (I could maybe with a reverse proxy but I don't host myself dataseer.ai)

so something like app-sn.dataseer.ai... 

They are nicer solutions but it would involved some development (for example to put the authentication at the gateway and direct queries to the right server based on user organization - we might need to move to that at some point if traffic is high!).

**Comment by timvines19** [comment]
That domain works for me - must have been the https. Traffic will be very low for this server, but having it at app-sn.dataseer.ai would be very neat.

Tim

**Comment by kermitt2** [comment]
I changed the DNS, redeployed a new certificate for this subdomain, and updated the local apache2 - it looks it's okay now with app-sn.dataseer.ai
