### ISSUE TITLE
automate report generation

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#160]
Once an article reaches the 'Finish' screen, the annotator or curator has the ability to automatically generate a DataSeer report for that article. 

This report consists of a template with fields that can be populated with metadata and other information from the DS UI. Here's an example of a manually generated report:

https://drive.google.com/file/d/1I6NuqpBIqmZXUsNa-yJkyxmnPRyvFN7E/view?usp=sharing

**Comment by timvines19** [comment]
Attached is the Word template

[DataSeer report template.docx](https://github.com/DataSeer/dataseer-web/files/5793594/DataSeer.report.template.docx)

**Comment by timvines19** [comment]
generating this report is not necessary if we can implement #165

**Comment by Souad314** [comment]
ASAP likes the idea of Status Report Word Docs

If they could be automated, it would save so much time, especially since we're expecting increasing quantities of uploads per month.
[DataSeer Status Report - Guillén-Samander et al. 2021.docx](https://github.com/DataSeer/dataseer-web/files/6430050/DataSeer.Status.Report.-.Guillen-Samander.et.al.2021.docx)

There's specific formats and organizing for ASAP, but having theirs be the template would be an excellent start.

Here's an updated example of a status report for them, 
Notably the datasets are organized by data type, but the dataset # remains the same (to keep its relative position in the article's text known).
The Dataset name is currently manually moved to underneath the dataset number, but I'll make a separate issue for that in a moment.
We're currently manually copying the Finish page and reformatting and manually copying from the wiki, it's a little tedious.

**Comment by NicolasKieffer** [comment]
@timvines19 @Souad314 
Could I have some links of gdocs reports with the "final structure" ("samples" or "real" reports)?
I need some examples to build the .docx template
