### ISSUE TITLE
metadata problem

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#269]
The metadata display for this article has multiple identical affiliations:

https://app.dataseer.ai/dataseer/documents/6076f672fe13c63fea4127d2/metadata

![Screen Shot 2021-04-16 at 11 38 44 AM](https://user-images.githubusercontent.com/49563305/115177926-0e8abd00-a085-11eb-8a26-70d34f89d9c7.png)

**Comment by NicolasKieffer** [comment]
@kermitt2 This problem come form data extracted from [TEI file](https://app.dataseer.ai/dataseer/api/documents/6076f672fe13c63fea4127d2/tei/content)
Should I update code to ignore same affiliations (basic text comparison)?

**Comment by kermitt2** [comment]
The extraction is actually "correct" in the sense that the same header is repeated two times on page 1 and on page 54, so the affiliations are repeated because there is a default logic in GROBID to rather put too much than too little :)
There is also no affiliation duplicate check for the moment, because I have never seen so far an article with two times a full header.

The best would be to ignore the same affiliation in the client yes, this is faster, given that I don't plan to come back to affiliations in GROBID as they are now (I plan a more deeper re-implementation of the affiliation model in the next months).

**Comment by timvines19** [comment]
Given that this is so rare I think can ignore this for the moment. If it occurs in another document we'll reopen this issue
