### ISSUE TITLE
incorporate Figure Legend text into process

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#395]
Our pilot with ASAP has shown that we need to do more with figure legends: some of the articles they've sent us contain datasets that are mentioned only in the figures, and in other cases they want to link a data sentence in the methods to the corresponding sentence in the figure legends.

would it be possible to 

a) allow the ML to search for datasets in table and figure legends, rather than exclude them, and 

b) make the text of figure legends selectable so that users can add/remove datasets from them?

Change (b) would probably also help a lot with issues of text being non-selectable described in #313

**Comment by kermitt2** [comment]
Hi Tim, 

b) figure captions are already selectable by the user:

![Screen Shot 2021-06-07 at 21 58 22 ](https://user-images.githubusercontent.com/2340795/121080297-8cdd2300-c7db-11eb-88f2-ee52665e070f.png)

If the text of a figure caption cannot be selected, it might be a structure recognition issue, but normally almost all text of an article can be selected (except page header, biblio section, ...)

a) The problem is that even if we allow the machine learning to consider that dataset sentences can be found in figure caption, it is machine learning and the decision to consider a section as relevant for introducing datasets is based on training data. We have no dataset so far in caption in the training data, so caption will never be selected. We can tweak, but this will result in false positives.

**Comment by timvines19** [comment]
OK, thanks for the explanation. For the moment we'll just manually link datasets described in the Methods to the corresponding sentence in the figure captions
