### ISSUE TITLE
Missing Author Information (3 separate instances)

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#397]
It seems as though in some instances authors are missing from the Metadata and Finish pages of the document:

[Hardy Vavouraki et al 2021 Published.pdf](https://app.dataseer.ai/dataseer/documents/60b0285101aacd5baf0a660f?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjBiMDI4NTEwMWFhY2Q1YmFmMGE2NjBmIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjIyMTU3NDA4LCJleHAiOjE2MjQ3NDk0MDh9.DWxlXXcAcIDAN-5dNGlwgBQviqXGbvjXTZFLlOP6OUM)

![image](https://user-images.githubusercontent.com/81999469/121427456-983e6480-c929-11eb-86a5-b7fca8266953.png)

![image](https://user-images.githubusercontent.com/81999469/121427525-aab89e00-c929-11eb-80b5-fc6fe609806b.png)

[DeCamilli Hancock-cerutti et al 2021 pre-preprint paper 06042021.pdf
](https://app.dataseer.ai/dataseer/documents/60ba82cb01aacd5baf0a6742?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjBiYTgyY2IwMWFhY2Q1YmFmMGE2NzQyIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjIyODM1OTU0LCJleHAiOjE2MjU0Mjc5NTR9.QHAypzEPGiyDT1-oW2RhVesGvXchHBWtKJFaYCaJM5w)
![image](https://user-images.githubusercontent.com/81999469/121429191-7fcf4980-c92b-11eb-9650-f87a28dc98c1.png)

![image](https://user-images.githubusercontent.com/81999469/121429316-9e354500-c92b-11eb-910b-4072fbb8973b.png)

[Hurley_OliviaHarding et al. 2021.04.12 Preprintl.pdf](https://app.dataseer.ai/dataseer/documents/608969e26a24cc3c8cb3bb61?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjA4OTY5ZTI2YTI0Y2MzYzhjYjNiYjYxIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjE5NjE4MzIxLCJleHAiOjE2MjIyMTAzMjF9.wyw-2QL3yVliV9GZqpDNfSHOfNPw31DzCQiYMGzXUMM)
![image](https://user-images.githubusercontent.com/81999469/121430074-7eeae780-c92c-11eb-9ab5-68d4b31f99a0.png)

![image](https://user-images.githubusercontent.com/81999469/121430142-9629d500-c92c-11eb-9df6-c14483f96960.png)

**Comment by NicolasKieffer** [comment]
This is because some "author identities" are not available in the TEI (generated by GROBID)

For exemple:
[DeCamilli Hancock-cerutti et al 2021 pre-preprint paper 06042021.pdf](https://app.dataseer.ai/dataseer/documents/60ba82cb01aacd5baf0a6742?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjBiYTgyY2IwMWFhY2Q1YmFmMGE2NzQyIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjIyODM1OTU0LCJleHAiOjE2MjU0Mjc5NTR9.QHAypzEPGiyDT1-oW2RhVesGvXchHBWtKJFaYCaJM5w)
[The generated TEI file (containing the data used by the dataseer-web application)](https://app.dataseer.ai/dataseer/api/documents/60ba82cb01aacd5baf0a6742/tei/content?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjBiYTgyY2IwMWFhY2Q1YmFmMGE2NzQyIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjIyODM1OTU0LCJleHAiOjE2MjU0Mjc5NTR9.QHAypzEPGiyDT1-oW2RhVesGvXchHBWtKJFaYCaJM5w)
![image](https://user-images.githubusercontent.com/16922410/121436666-4d503b80-c981-11eb-8686-eb5b4154794b.png)
