### ISSUE TITLE
Public URL requires login

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#480]
Getting the public URL for this report still takes me to a login page

https://app.dataseer.ai/dataseer/documents/612e6d659714ef353c01d7e4/datasets

See this Loom:

https://www.loom.com/share/7db55c66b55f409cb556eecb0a6b1f04

Here's the Public URL I get

https://app.dataseer.ai/dataseer/documents/612e6d659714ef353c01d7e4/datasets?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjEyZTZkNjU5NzE0ZWYzNTNjMDFkN2U0IiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjMwNDMyNjI3LCJleHAiOjE2MzMwMjQ2Mjd9.v5DVSxa9n2KopYMFMiiLPDihjyX6-BEzx3lGrqJ5WB4

**Comment by NicolasKieffer** [comment]
This bug does not come from public URL (but from GUI i think*) because public URL works on a "private tab" (chrome)

![image](https://user-images.githubusercontent.com/16922410/131595333-bf5653b2-4711-4d49-a5ec-9c7511241cda.png)

I will fix this behavior.

*your account token is stored in the cookies of your navigator. When this cookie is not valid anymore (eg after a logout or after 2 mounth), the GUI will "automatically" redirect you to the signin form to refresh your account token.
